### PR TITLE
Support "OR" in WHERE clauses

### PR DESCRIPTION
**Pull request by cbornhoft**

### CODE REVIEW

**Comment by jkufner** [comment]
How the SQL query will look like when you run the following code?

    $fpdo->select('foo')->where('a = 1')->whereOr('b = 2');

**Comment by cbornhoft** [comment]
That should produce:

    SELECT foo.* FROM foo WHERE a = 1 OR b = 2

**Comment by jkufner** [comment]
And what about:

    $fpdo->select('foo')->where('a = 1')->whereOr('b = 2')->where('c = 3');

What should it produce?

    SELECT foo.* FROM foo WHERE a = 1 OR b = 2 AND c = 3
    SELECT foo.* FROM foo WHERE a = 1 OR b = 2 OR c = 3
    SELECT foo.* FROM foo WHERE a = 1 AND b = 2 AND c = 3

The first seems right, but does not make sense as it is ambiguous and result of the query depends on the order in which the where() methods are called. The other two results are clearly wrong, but the code looks like it sets separator according to the last called method. Therefore, if we change order of the method calls, the query changes in very unexpected way. I guess the best option here is to throw an error when the methods are mixed.

**Comment by cbornhoft** [comment]
@jkufner @sanabria91 see #255 and #256 for the updated implementation of this. It now supports any combination of AND and OR

**Pull request closed without merging**
