### PR TITLE
Move library in FluentPDO namespace

### PR DESCRIPTION
**Pull request by vdelau**
This branch has:
- Introduced a FluentPDO namespace
- Moved classes to src, to be more composer-esque
- Replaced the include statements with composer autoloader configuration
- Fixed tests to use autoloader and namespace
- Ran fabpot/php-cs-fixer, afterwards replaced spaces by tabs to keep diff in check

That last step was maybe a bit ambitious to do before committing the other changes. If needed, that could be undone.

### CODE REVIEW

**Comment by maldoinc** [comment]
Hello @vdelau, thanks for the PR.

I personally have no issues against adding the namespaces, in fact it's on our todo list.

However, two things to note from this PR:

1. We haven't decided yet if we want to add namespaces to this release yet. We're planning on working on a new release tagged 2.0 which would be the one to have namespaces for sure. Adding them now is a sure way to break existing code with a simple `composer update` (since lots of people are going to be using dev-master as their pull branch)
2. You have added different code formatting. While I agree that PSR-2 is the way to go, there is no need to mix the current formatting style with PSR-2. When we do that the whole project is going to get updated at one glance.


Paging @cbornhoft @lichtner @StefanYohansson regarding these two points.

**Comment by vdelau** [comment]
Both notes are perfectly understandable and I agree with them. I'd be happy to redo this exercise, keeping the formatting intact. The changes in the library itself are pretty trivial.

Maybe this could be the start of a 2.0-alpha branch if you feel comfortable with that.

**Comment by cbornhoft** [comment]
I think most of these changes are okay for this version.

However, removing the includes is a breaking change for anyone not using composer or another autoloader.

**Comment by StefanYohansson** [comment]
Hey @vdelau, thanks for the awesome PR. @maldoinc notes is useful and makes sense. We can't change this version in this way. But we can use your idea:
We can use it for the "2.0-alpha" branch. It will save our effort in this rewrite.

**Comment by afk** [comment]
Hi everyone,

how about taking namespacing even further by:
- grouping similar classes in sub-namespaces (e.g. querys: `FluentPDO\Query\Select`)
- removing clutter from the helper classes (`FluentPDO\Utils` instead of `FluentPDO\FluentUtils`)

**Comment by cbornhoft** [comment]
@afk This is part of plan for the 2.0 release.

**Comment by cbornhoft** [comment]
Implemented in #217

**Pull request closed without merging**
